name: PaperRPGToolkit
version: '${version}'
main: daylightnebula.paperrpgtoolkit.PaperRPGToolkit
api-version: 1.19
load: STARTUP
authors: [ DaylightNebula ]
description: An RPG Toolkit for Minecraft Paper Servers
commands:
  getcustomitem:
    description: Get custom item
    usage: /getcustomitem <name or id> [amount]
  startquestchain:
    description: Start a quest chain for the sender
    usage: /startquestchain <quest chain id>
  endquestchain:
    description: End the senders current quest chain
    usage: /endquestchain
  advancequestchain:
    description: Advance the senders current quest chain
    usage: /advancequestchain
  spawnnpc:
    description: Spawn NPC
    usage: /spawnnpc [<x> <y> <z>] [<pitch> <yaw>]
  removenearbynpcs:
    description: Remove nearby NPCs
    usage: /removenearbynpcs [kill radius]
  spawnmob:
    description: Spawn Custom Mob
    usage: /spawnmob <mob id>
  removenearbymobs:
    description: Remove nearby custom mobs of a certain type or of all types
    usage: /removenearbymobs <mob id> <range>